version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  nextjs:
    container_name: nextjs_app
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env.local
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
